# https://kargo.akuity.io/how-to-guides/managing-credentials
apiVersion: v1
kind: Secret
metadata:
  name: repo-argocd-image-tag-creds
  namespace: kargo
  labels:
    kargo.akuity.io/secret-type: repo-creds
stringData:
  type: git
  url: https://gitlab.com/quickbooks2018/argocd-image-tag.git
  username: kargo # or you can use 'gitlab' if username is not needed
  password: <gitlab-token>
