---
apiVersion: v1
kind: Namespace
metadata:
  name: project-1
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: project-1
spec:
  subscriptions:
    repos:
      git:
      - repoURL: https://gitlab.com/quickbooks2018/argocd-image-tag.git
        branch: main
      images:
      - repoURL: registry.gitlab.com/quickbooks2018/foo
        semverConstraint: ^49
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://gitlab.com/quickbooks2018/argocd-image-tag.git
      writeBranch: main
    argoCDAppUpdates:
    - appName: foo-dev
      appNamespace: argocd
