apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: foo-dev
            cluster: dev-cluster
            url: https://kubernetes.default.svc

          - env: staging
            namespace: foo-staging
            cluster: in-cluster
            url: https://172.18.0.2:6443

          - env: prod
            namespace: foo-prod
            cluster: prod-cluster
            url: https://172.18.0.3:6443
  template:
    metadata:
      name: 'foo-{{env}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: argocd-example
      source:
        repoURL: https://gitlab.com/quickbooks2018/argocd-image-tag.git
        targetRevision: HEAD
        path: apps/charts/foo
        helm:
          valueFiles:
            - '{{env}}-values.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true